name             'github'
maintainer       'Sous-Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'A Library Cookbook for interacting with the Github API'
version          '0.3.2'
chef_version     '>= 15.3'

supports 'ubuntu'
depends 'libarchive'
